name = "Krater Pack"
author = "Mofo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e404bd21ad82c145b8c1d9f75a202743c5a6833d024c2478d8bbcdd9cd872d03"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
