name = "Krater Pack"
author = "Mofo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43e3991f40fa4a9ea7e5faad598368c121d0a5448790310388c4f4274de8813"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
